### ISSUE TITLE
broken links in README

### ISSUE THREAD

**Issue by VladimirAlexiev** [eclipse-tractusx/knowledge-agents-edc#185]
https://github.com/eclipse-tractusx/knowledge-agents-edc
has a broken link:
https://github.com/eclipse-tractusx/knowledge-agents-edc/blob/main/gent-plane/agent-plane-protocol/src/main/java/org/eclipse/tractusx/agents/edc/rdf/RDFStore.java

The correct link is
https://github.com/eclipse-tractusx/knowledge-agents-edc/blob/main/agent-plane/agent-plane-protocol/src/main/java/org/eclipse/tractusx/agents/edc/rdf/RdfStore.java
(There are two typos).

Please check all other links as well, thanks!

**Comment by drcgjung** [comment]
we will include a link checker action in the long run. thx for reporting.
