### ISSUE TITLE
Add `helm upgrade` workflow

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/knowledge-agents-edc#26]
The current [Lint and Test Charts](https://github.com/eclipse-tractusx/knowledge-agents-edc/blob/main/.github/workflows/helm-chart-lint.yml) workflow should be enhanced by a `helm upgrade` step, that verifies, that an upgrade from the latest released Chart version to the current chart present in the repo is possible.

This is not blocking the current release for Tractus-X 3.2, since there was not knowledge-agents-edc release before anyways, but should be added for future checks.

**Comment by drcgjung** [comment]
Yeah, problem here is the same as with chart testing: there is an external vault dependency in each of the EDC charts too which makes "kind" deployment unuseful (both planes would not start without vault). I will try to figure out how we could reach that with 29.12

**Comment by SebastianBezold** [comment]
Ok. Is there at least one chart, that does only use open source dependencies? HashiCorp Vault for example should be integrateable as dependency of the chart and just deploy it together.

**Comment by drcgjung** [comment]
> Ok. Is there at least one chart, that does only use open source dependencies? HashiCorp Vault for example should be integrateable as dependency of the chart and just deploy it together.

In Principle yes, but the vault needs to be populated with a few reasonable secrets (valid certs and public keys, aes keys, ...) 
I have not managed to find out how to do that with hashicorp chart, would take another week I guess ,sorry.
But I have a solution that at least proves that when following the documentation, it would work "nearly" out of the box (ct install on your machine, for example). I'll keep you up-to-date.
At least I found a problem in the dataplane test pod this way ,-)

**Comment by SebastianBezold** [comment]
Reopening, because GitHub does not recognizes "not closes #26" :) just saw "closes #26".

To your point @drcgjung: Fair enough. I think this sounds like a "initcontainer might help here" solution. We can check that out after the current release phase
