### ISSUE TITLE
Dockerhub images do not start

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/knowledge-agents-edc#46]
# Description

All images under 

https://hub.docker.com/search?q=tractusx%2Fagentplane-hashicorp

and

https://hub.docker.com/search?q=tractusx%2Fagentplane-azure-vault

currently do not start.

# Error

Error: Invalid or corrupt jarfile edc-dataplane.jar

# Should be

Image should start normally.

**Comment by drcgjung** [comment]
Reason is that the Dockerfiles https://github.com/eclipse-tractusx/knowledge-agents-edc/blob/main/agent-plane/agentplane-azure-vault/src/main/docker/Dockerfile and https://github.com/eclipse-tractusx/knowledge-agents-edc/blob/main/agent-plane/agentplane-hashicorp/src/main/docker/Dockerfile currently need two --build-args (JAR,LIB) to correctly copy over the binary artifacts from maven to the docker environment.

This has not been noticed, because in the tests, the mvn -Pwith-docker-image is used before (which correctly sets the args and creates local images which are valid).

**Comment by florianrusch-zf** [comment]
When will the problem be fixed?

**Comment by drcgjung** [comment]
> When will the problem be fixed?

Prob is that in order to fix the 1.9 release, we need to first delete some github maven packages for which we need an admin. I will try to talk to sig-infra to find someone with permissions and time.

Until then you could temporarily switch to a working docker image like this

my-connector:
  dataplanes:
    dataplane:
      image:
        repository: ghcr.io/catenax-ng/tx-knowledge-agents-edc/agentplane-hashicorp
        tag: 1.10.2-SNAPSHOT

Thx for your patience.

**Comment by florianrusch-zf** [comment]
Of course, the release should be removed or fixed. But in the mean time it should be possible to do a hotfix release or not?

**Comment by drcgjung** [comment]
I need sig-infra to look at it in each case unfortunately, I gave them a heads up.
