### ISSUE TITLE
Use proper code style/formatting

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/knowledge-agents-edc#57]
The source code of this project does not follow any code style guide. 

- The indentation is done partly with spaces, partly with tabs.
- Partly there are spaces at the end of lines
- Partly there are empty lines with some spaces
- Partly [a blank line at the end of files](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) is missing.
- Sometimes spaces are set around the equal sign in variable assignments, sometimes not.
- Sometimes the code is way too nested and not decoupled enough. E.g. I discovered a [function](https://github.com/eclipse-tractusx/knowledge-agents-edc/blob/64e0598b84f14e4979040e0741732138d238e4f3/agent-plane/agent-plane-protocol/src/main/java/org/eclipse/tractusx/agents/edc/AgreementController.java#L123-L163) which goes 8 levels deep
- Sometimes if-statements use a space between `if` and the `(`, sometimes not.
- ...

## Suggestion

Pick a code style, follow it and enforce it with some automated tests in the CI pipeline.

For general files (not java) I also recommend to use a proper IDE/Editor which trims automatically trailing spaces, etc.
Also I would recommend to add an [`.editorconfig` file](https://editorconfig.org/). Most of the IDE's/Editors are supporting it out of the box.

**Comment by drcgjung** [comment]
point is very valid, we got spotless already configured, but not activated. Will see for rules in the other projects and then come up with a proposal.
