### ISSUE TITLE
Helm Chart is not usable standalone

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/knowledge-agents-edc#58]
If you want to deploy the PostgreSQL and HashiCorp vault instance from the dependencies of the helm charts, the linking between the EDC and the DB/Vault is not working properly.

E.g. for HasiCorp vault in the `values.yaml` files the attribute `vault.hashicorp.url` is set to the following: `http://{{ .Release.Name }}-vault:8200`. But this will only work if the value is passed as an parameter to the `tpl` function within the templates. This is not the case sadly. Same for the PostgreSQL connection.

I will provide a PR to fix this.

**Comment by drcgjung** [comment]
thanks for this heads up. And even more for directly fixing the issue. If you could change the chart version in the PR, I would care for backporting this to the 1.9 release line ....
