### ISSUE TITLE
Story "Improve Agent-EDC Management Interactions"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-edc#96]
# Story "Improve Agent-EDC Management Interactions"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a KA participant, I want that the KA Agent Plane efficiently communicates with the Control Plane such that negotiations will take place in a shorter, more stable fashion.

## Acceptance Criteria

- analyze the possibilities to use the EDR management API including callbacks.
- implement an improvement

## Estimation 

4 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/287#issuecomment-1770545119_

**Comment by drcgjung** [comment]
From a resource management perspective, the EDR solution was suboptimal and is rejected.
