### ISSUE TITLE
Story "Implement Data-Plane Chart"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-edc#98]
# Story "Implement Data-Plane Chart"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want the KA Agent Plane to be deployable alongside EDC charts such that I can seamlessly extend my existing EDC deployment.

## Acceptance Criteria

- find out how the dataplane can register/deregister itself in the control plane
- implement startup/teardown actions in the agent plane deployment
- make the agent plane chart refer to values in the umbrella chart
- extend the ct test 
- remove the old charts

## Estimation 

10 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/286#issuecomment-1770924931_

**Comment by drcgjung** [comment]
Belongs to https://github.com/eclipse-tractusx/sig-release/issues/390
